export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>{/* 头部内容 */}</head>
      <body>
        {/* 所有内容都应该在 body 内 */}
        <div className="your-container">{children}</div>
      </body>
    </html>
  );
}
